### ISSUE TITLE
Missing MHonArc module

### ISSUE THREAD

**Issue by racke** [sympa-community/MHonArc#12]
Installation:

`
cpanm MHonArc::UTF8
`

Executing mhonarc:

```
Can't locate MHonArc.pm in @INC (you may need to install the MHonArc module) (@INC contains: lib /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/x86_64-linux /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0 /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/x86_64-linux /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0) at /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/mhamain.pl line 29.
BEGIN failed--compilation aborted at /home/racke/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/mhamain.pl line 29
```

**Comment by ldidry** [comment]
Sorry 😓

I just fixed that and pushed the version 2.6.24 to CPAN.

**Comment by racke** [comment]
Yes, 2.6.24 works for me. Thanks for the quick fix

**Comment by racke** [comment]
But in fact there *should* be such a module. It is confusing otherwise and we can't simply do `cpanm MHonArc`.

**Comment by ldidry** [comment]
Indeed. But when the PAUSE upload bug drove me crazy, I reverted the `MHonArc.pm` file I created.

I suggest to have at least one Sympa release with MHonArc 2.6.24, then we will modify MHonArc a bit more.
