### ISSUE TITLE
Wrongly recogniced "^From " in the mail-body

### ISSUE THREAD

**Issue by schnudd31do3** [sympa-community/MHonArc#19]
When there is a "From " at the beginning of a line inside the body of the email, it will be recognized as new email from that point. Example output:

Reading /usr/local/src/test_info-0383.mbox .read_mail_body(): Body data loaded into memory
read_mail_body(): Calling readmail::MAILread_body
MAILread_body: charset: us-ascii
**Warning: No end boundary delimiter found in message body**
MAILread_body: charset: us-ascii
MAILread_body: charset: utf-8
read_mail_body(): readmail::MAILread_body DONE
.
**Warning: Could not parse date for message**
         Message-Id: <8480dea9fadbf7c8f84fe003fb7ef2f7@NO-ID-FOUND.mhonarc.org>
         Date:
read_mail_body(): Body data loaded into memory
read_mail_body(): Calling readmail::MAILread_body
MAILread_body: charset: us-ascii
read_mail_body(): readmail::MAILread_body DONE

Writing mail ..
Writing /usr/local/src/mhonarc/maillist.html ...
Writing /usr/local/src/mhonarc/threads.html ...
Writing database ...
**2 new messages**
2 total messages

The first "^From " in an email is taken from the email header. The first warning here is coming from the wrongly recognized second "^From " which is inside the body. Therefore it thinks that there had to be an end delimiter before finding the second "From ".

The mistake is coming from not verifying after **each** "^From " if it is **followed by a real eamail address** (e. g. containing "@") **AND** if it has a **colon** like "**^From:** "

In my version 2.6.19-2.2 I isolated in the /usr/share/mhonarc/mhamain.pl the area around the line 26637, where it was missleaded:
![image](https://github.com/sympa-community/MHonArc/assets/72391822/321a8fd9-967a-459d-9112-3aaaf4df272b)

**Comment by ikedas** [comment]
With the mbox format, a line beginning with a bare "`From `" indicates the start of a message. When a line beginning with "`From `" appears in the message body, it must be escaped (see also the [article about mbox](https://en.wikipedia.org/wiki/mbox) on Wikipedia).

**Comment by schnudd31do3** [comment]
You are right, '_With the mbox format, a line beginning with a bare "From " indicates the start of a message._'. But there is **no validiation** in your code **if a real email address is following** at that point. Therefore **all** further appearances of "From " in the same email inevitably leads erroneous new entries in the mhonarc-archive. Additionally you get wrong warnings and wrong error messages.

If I understand it right, you expect the writer of an email has to escape a "From " in his email like "\From\ ..."? Nobody from our employees would accept this. On the other hand, modifying email-bodies afterwards by escaping "From" would be not legal because of forgery.

**Comment by ikedas** [comment]
> If I understand it right, you expect the writer of an email has to escape a "From " in his email like "\From\ ..."? Nobody from our employees would accept this. On the other hand, modifying email-bodies afterwards by escaping "From" would be not legal because of forgery.

Yes, in mbox format, the lines beginning with bare "`From `" should be escaped as "`>From `", no matter what follows (please read the article of Wikipedia).

Conversely, anything that does not escape the bare "`From `" in the message body is not considered to be in mbox format.

**Comment by schnudd31do3** [comment]
I have read the article **twice**. Thanks.

The mbox file is created from mailman3. I have no influence to the created structure:

From xxxx.yyyyy@xxxx.yy Wed May 24 08:10:10 2023
From: xxxx yyyy <xxxx.yyyy@xxxx.yy>
To: list1@xxxx.yy
Subject: Blabla
Date: Mon, 22 May 2023 13:53:52 +0000
Message-ID: <313817c57e434657b1204bc8095dbc7f@xxxx.yy>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="===============5317628564649367459=="

--===============5317628564649367459==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Dear colleagues,

...

From xxxx vxx.yy here is the possibility to activate the extra delay for calibration ...
...
--===============5317628564649367459==--

As I wrote, it is not allowed by law, to modify emails afterwards to work arround this bug. And users do not accept that they can only write ">From" at the beginning of a sentence. Any reader of the email would assume such a spelling as a spelling mistake.

**Comment by ikedas** [comment]
If it is not escaped correctly, it is not in mbox format. 

Note that, it is not the author of the email that must escape "`From `", but the creator of the data in mbox format. 
 On the other hand, applications that display mail in mbox are expected to unescape "`>From `".

It is simply a format for compiling email messages, not tampering with the email itself.

(Actually, the similar escaping/unescaping are done when delivering mail via SMTP protocol, but we wouldn't call that tampering, would we?)

**Comment by schnudd31do3** [comment]
For testing I modified the mbox file with ">From ...". Mhonarc created a html file, containing: "`&gt;`From xxxx xx.x here is the possibility to activate the extra delay for calibration..."

This means, the inserted ">" is visible on the html site and will be an illegal modification of an original emal.

**Comment by ikedas** [comment]
If you think the mbox format is inappropriate, why not use the MH format? It does not do escaping.

**Comment by schnudd31do3** [comment]
Mailman3 only supports the mbox format. So, the MH format would neither work for me nor does it solve the existing bug in the mbox filter.

But in the meantime I've gotten the feeling that perhaps one might not really be interested in acknowledging this error.

**Comment by ikedas** [comment]
No.  "validiating the sender address" is not a part of processing mbox.  In mbox, simply "`From `" must be escaped.

As you will understand if you read the Wikipedia article, the mbox format is not a very stable standard (there are several different variants). In other words, not that I am not interested in acknowledging "error". but rather I think mbox is not a recommended format.

On the contrary, I wonder why you insist on mbox instead of the MH format about which there is nothing unstable.

**Comment by schnudd31do3** [comment]
Please read my post: "**Mailman3 only supports the mbox format.** ...". that is my problem.

In my opinion it is not a problem of the lazy mbox standard, but its weak implementation. There is no restriction inside the definition to not validiate the sender email address.

**Comment by ikedas** [comment]
> Please read my post: "**Mailman3 only supports the mbox format.** ...". that is my problem.

But the data you claim being in mbox format is not in mbox format.  Mailman3 is supposed to use the [mailbox](https://docs.python.org/3/library/mailbox.html) Python library, so it shouldn't have such a elementary bug... I can't figure it out.

Besides, if you are using Hyperkitty, Hyperkitty-Sync ([hksync](https://pypi.org/project/hksync/)) may export email in Maildir format.  Both Maildir and MH save each message in a separate file and do nothing like escaping.   In MH, the files in the folder are simply named with integer sequential numbers. Thus, if you rename the files after exporting them to Maildir, it will become MH.

**Comment by schnudd31do3** [comment]
There is an additionaly way to get the mails aout of mailman3. There is a button for downloading the mails in a defined time range. The downloaded file is a zipped mbox, which I feed to mhonarc. For compatibility reasons of very old archives, started with mailman2, it was the easiest way to step over to mailman3.

Thanks for your suggests with hyperkitty. I will check it.

But can we stay on the topic of mbox errors please? Would you please take a look at the place in the code? I would be happy to try a patch from you.

**Comment by ikedas** [comment]
> But can we stay on the topic of mbox errors please? Would you please take a look at the place in the code? I would be happy to try a patch from you.

You suggested a solution:

> The mistake is coming from not verifying after each "^From " if it is followed by a real eamail address (e. g. containing "@") AND if it has a colon like "^From: "

However, that is not acceptable because it does not conform to the mbox format. The reason is that other thing than email address may be placed just after the "From " indicating the beginning of the message.

In the first place, it does not solve the problem fundamentally --- it only imposes another restriction that the line "From &lt;email@addr.ess>" cannot be placed in the body of the message.

**Comment by schnudd31do3** [comment]
The created structure in my case looks like the example listed in the link: https://en.wikipedia.org/wiki/Mbox
![image](https://github.com/sympa-community/MHonArc/assets/72391822/88191ba4-e467-4a41-9d31-0b41b1e4e138)

Based on this information, mhonarc should actually assume the existence of a following line with "From:" after "From ", in order to recognize a real mail header in it. Since there is no "From:" line after the "From" line in the body of the email, mhonarc must not recognize a new email in this case, especially since there is no valid delimiter with 3 empty lines in the body of the email.

**Comment by ikedas** [comment]
> Based on this information, mhonarc should actually assume the existence of a following line with "From:" after "From ", in order to recognize a real mail header in it.

No.

It is an example.  Not all messages have “From:” line after “From “ line.

To know about format of email messages, learn by books and/or web articles written by experts.

If you have no particular new suggestions, I will close this Issue.

**Comment by schnudd31do3** [comment]
I would like to further discuss, because the last thing is not answred.

I made an experient. I eliminated all blank lines after the "From" in the body and rerun my test. For a valid delimiter, mhonarc should have seeked for the 3 new lines and only then he should "recognice" an new message. But he doesnt. He still splits the one email into two entries, generating an unknown sender for the second entry

**Comment by ikedas** [comment]
Again, the data you presented is not in mbox format, so any effort to make it processable as mbox format is pointless. If there are no more new and meaningful suggestions, this issue is closed.

**Comment by schnudd31do3** [comment]
There are several valid mbox formates and I am sure that mailman3 is keeping the mbox specification.

You did not answer my experimet. This makes clear that  mhonarc seems not searching for the 3 new lines as valid deliminiter to search for the next **valid** "From".

I would like to decide how to close the case myself. Thanks.

**Comment by ikedas** [comment]
I don’t know why you take care of “3 new lines”, because it is never related to the mbox format.

There seems no more suggestions, then it’d be better to close this issue.

**Comment by schnudd31do3** [comment]
Anything else than threaten to close the case? Is this the quality to clearify and / or improoving?

Have you seen https://www.freeviewer.org/mbox/forensics.html, section "MBOX Ending pattern"

**Comment by ikedas** [comment]
I wrote:

> To know about format of email messages, learn by books and/or web articles **written by experts**.

There are no evidences that mbox format always separated by “3 new lines”.

**Comment by ikedas** [comment]
Close.
