### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by ldidry** [sympa-community/MHonArc#7]
- [x] Merge `develop` into `master`
- [x] Update [CHANGES](https://github.com/sympa-community/MHonArc/blob/master/CHANGES)
- [x] Update version number to 2.6.20 in [MHonArc.pm](https://github.com/sympa-community/MHonArc/blob/develop/lib/MHonArc.pm)
- [x] Create tarball (`perl Makefile.PL; make; make tardist`) and upload it to PAUSE¹
- [x] Merge `master` into `develop`
- [x] Rebase pending PR with `develop` if needed
- [x] Close the relative [milestone](https://github.com/sympa-community/MHonArc/milestone/1)

¹ Need for the community to have co-maintainership of MHonArc on PAUSE

**Comment by ldidry** [comment]
@racke @ikedas @dverdin I think that now we have have the comaintainership on PAUSE, it’s time for a new release (2.6.20). Is that OK for you ? Once I got at lease 2 "Go", I’ll do all the stuff listed in this issue.

NB: I merged #9, which adds the github url for issue tracking and #4 (code tidying). #4 was first associated to the 2.6.21 milestone but it seemed ok to me to merge it now.

**Comment by racke** [comment]
@ldidry yes please go ahead, that's about time for the release :grimacing:

**Comment by ikedas** [comment]
@ldidry, it's OK for me. Thanks for your work!

**Comment by racke** [comment]
@ldidry Please let us know when the module is released to CPAN.

**Comment by ldidry** [comment]
I uploaded it but it seems there is a problem:

<details>
<summary>Click to see the error message from PAUSE</summary>
<pre><code>The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: LDIDRY (Luc Didry)
  Distribution file: MHonArc-2.6.20.tar.gz
  Number of files: 544
  *.pm files: 122
  README: MHonArc-2.6.20/README.txt
  META-File: MHonArc-2.6.20/META.json
  META-Parser: Parse::CPAN::Meta 1.4414
  META-driven index: no
  Timestamp of file: Mon Sep 14 09:22:58 2020 UTC
  Time of this run: Mon Sep 14 09:32:50 2020 UTC

This distribution name will only be indexed when uploaded by users with
permission for the package MHonArc. Either someone else has ownership
over that package name, or this is a brand new distribution and that
package name was neither listed in the 'provides' field in the META file
nor found inside the distribution's modules. Therefore, no modules will
be indexed.

Further details on the indexing attempt follow.


The following packages (grouped by status) have been found in the distro:

Status: No permissions for distribution name
============================================

     module : MHonArc::Char
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/Char.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::Char::JP
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/Char/JP.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::Char::KR
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/Char/KR.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleArabic
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleArabic.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleCenteuro
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleCenteuro.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleCroatian
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleCroatian.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleCyrillic
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleCyrillic.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleGreek
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleGreek.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleHebrew
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleHebrew.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleIceland
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleIceland.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleRoman
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleRoman.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleRomanian
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleRomanian.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleThai
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleThai.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::AppleTurkish
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/AppleTurkish.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::BIG5_ETEN
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/BIG5_ETEN.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::BIG5_HKSCS
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/BIG5_HKSCS.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1250
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1250.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1251
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1251.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1252
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1252.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1253
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1253.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1254
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1254.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1255
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1255.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1256
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1256.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1257
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1257.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP1258
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP1258.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP866
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP866.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP932
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP932.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP936
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP936.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP949
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP949.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::CP950
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/CP950.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::EUC_JP
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/EUC_JP.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::GB2312
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/GB2312.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::GOST19768_87
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/GOST19768_87.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::HP_ROMAN8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/HP_ROMAN8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_1
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_1.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_10
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_10.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_11
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_11.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_13
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_13.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_14
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_14.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_15
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_15.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_16
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_16.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_2
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_2.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_3
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_3.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_4
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_4.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_5
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_5.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_6
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_6.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_7
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_7.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::ISO8859_9
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/ISO8859_9.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_A
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_A.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_B
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_B.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_E
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_E.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_F
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_F.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_R
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_R.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI8_U
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI8_U.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI_0
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI_0.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::KOI_7
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/KOI_7.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharEnt::VISCII
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharEnt/VISCII.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::CharMaps
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/CharMaps.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::Encode
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/Encode.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleArabic
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleArabic.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleCenteuro
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleCenteuro.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleCroatian
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleCroatian.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleCyrillic
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleCyrillic.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleGreek
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleGreek.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleHebrew
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleHebrew.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleIceland
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleIceland.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleRoman
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleRoman.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleRomanian
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleRomanian.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleThai
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleThai.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::AppleTurkish
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/AppleTurkish.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::BIG5_ETEN
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/BIG5_ETEN.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::BIG5_HKSCS
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/BIG5_HKSCS.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1250
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1250.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1251
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1251.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1252
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1252.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1253
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1253.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1254
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1254.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1255
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1255.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1256
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1256.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1257
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1257.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP1258
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP1258.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP866
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP866.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP932
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP932.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP936
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP936.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP949
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP949.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::CP950
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/CP950.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::EUC_JP
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/EUC_JP.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::Encode
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/Encode.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::GB2312
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/GB2312.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::GOST19768_87
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/GOST19768_87.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::HP_ROMAN8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/HP_ROMAN8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_1
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_1.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_10
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_10.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_11
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_11.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_13
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_13.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_14
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_14.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_15
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_15.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_16
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_16.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_2
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_2.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_3
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_3.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_4
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_4.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_5
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_5.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_6
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_6.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_7
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_7.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::ISO8859_9
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/ISO8859_9.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_A
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_A.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_B
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_B.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_E
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_E.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_F
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_F.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_R
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_R.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI8_U
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI8_U.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI_0
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI_0.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::KOI_7
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/KOI_7.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::MapUTF8
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/MapUTF8.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::MhaEncode
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/MhaEncode.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

     module : MHonArc::UTF8::VISCII
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/UTF8/VISCII.pm
     status : Not indexed; LDIDRY not authorized for this distribution
             name

Status: Permission missing
==========================

     module : MHonArc
     version: 2.006020
     in file: MHonArc-2.6.20/lib/MHonArc.pm
     status : Not indexed because permission missing. Current registered
             primary maintainer is . Hint: you can always find the
             legitimate maintainer(s) on PAUSE under "View Permissions".

Status: Decreasing version number
=================================

     module : MHonArc::RFC822
     version: undef
     in file: MHonArc-2.6.20/lib/MHonArc/RFC822.pm
     status : Not indexed because MHonArc-2.6.19/lib/MHonArc/RFC822.pm in
             E/EH/EHOOD/MHonArc-2.6.19.tar.gz has a higher version
             number (0.01)

__END__
</code></pre>
</details>

I then checked that I have the right permissions on MHonArc on PAUSE, and it seems OK. I asked for a re-indexation. Now, we have to wait.

**Comment by racke** [comment]
Indeed weird ....

**Comment by ldidry** [comment]
Same error after asking for re-indexing :thinking:

**Comment by racke** [comment]
Contact PAUSE admins?

**Comment by ikedas** [comment]
>  status : Not indexed because permission missing. Current registered
>          primary maintainer is . Hint: you can always find the
>          legitimate maintainer(s) on PAUSE under "View Permissions".

Weird.  I confirmed we are co-maint of MHonArc.

>  status : Not indexed because MHonArc-2.6.19/lib/MHonArc/RFC822.pm in
>          E/EH/EHOOD/MHonArc-2.6.19.tar.gz has a higher version
>          number (0.01)

In [this commit](https://github.com/sympa-community/MHonArc/pull/3/commits/6e34a642f47e30d66206306b8b64a46fbaf82da1), changes such as
``` diff
+ use MHonArc;
+ our $VERSION = $MHonArc::VERSION;
```
seem not working as expected.  I guess Perl code migiht not be executed to detect version number during indexing by PAUSE: Instead, a literal version string should be written, like
``` diff
+ our $VERSION = '2.6.20';
```

**Comment by ldidry** [comment]
I see that the name of the primary maintainer is missing in PAUSE’s message (`Current registered primary maintainer is .`). It seems that I did something preventing PAUSE’s indexer to find the namespace.

For the `Status: No permissions for distribution name` (first part), I think that the problem is that I added a `$VERSION`, and since it’s not interpreted, we have `version: undef`.

I’ll revert the changes relative to the `$VERSION` that I made, and upgrade the version of `lib/MHonArc/RFC822.pm`. Do you think I can remove the version from it?

**Comment by ldidry** [comment]
> For the Status: No permissions for distribution name (first part), I think that the problem is that I added a `$VERSION`

Wrong: `MHonArc::UTF8::AppleArabic` simply doesn’t have any `$VERSION` defined.

I’ll contact the PAUSE admins before doing anything.

**Comment by ldidry** [comment]
I decided to revert my changes about the `$VERSION` (not pushed yet). Now, I only have `Status: No permissions for distribution name`. I asked PAUSE admins for advice (sympa-developpers in CC).

**Comment by ikedas** [comment]
> I’ll revert the changes relative to the `$VERSION` that I made, and upgrade the version of `lib/MHonArc/RFC822.pm`. Do you think I can remove the version from it?

It is recommended that all library files in the module have `$VERSION`, or some repositories (e.g. for cpanminus) may not index the module correctly.  I prefer to add a line
```perl
our $VERSION = '2.6.20';
```
to each `*.pm` file.

**Comment by ldidry** [comment]
Ok. Pretty annoying when changing the version, but ok.

**Comment by racke** [comment]
That's a Perl oneliner ....

**Comment by ldidry** [comment]
Yes, sure, but you need to think to do it when releasing a new version.

**Comment by ldidry** [comment]
That’s kind of weird that no version was in the modules before and pause indexing worked :thinking: 

Anyway, I asked for deletion of my faulty tarball, I need to wait until 18 september (friday) before being able to push my new version (I don’t want to increase the version number on each try).

I post that here as a reminder how to change version number everywhere:
```
find lib -type f | xargs -I % sh -c 'sed -e "s/2.6.21/2.6.22/" -i %;'
```

**Comment by ldidry** [comment]
I finally created a 2.6.22 version: even if the previous 2.6.21 files were deleted on PAUSE, I got a conflict when trying to upload a 2.6.21 package.

**Comment by ikedas** [comment]
> I finally created a 2.6.22 version: even if the previous 2.6.21 files were deleted on PAUSE, I got a conflict when trying to upload a 2.6.21 package.

You may try with e.g. 2.6.21_1, then if  things will go fine, you may upload 2.6.22.

suffix _1, _2,... means the unstable release after the last stable release (eg. 2.6.21_1 means such as 2.6.22beta).

**Comment by racke** [comment]
Too late, it is already on CPAN :grin:

**Comment by ldidry** [comment]
I just received¹ a mail from Neil Bowers, it’s a pb on PAUSE because MHonArc didn’t have a MHonArc.pm. TL;DR: he will try to fix the pb and trigger a reindexing of my latest upload.

¹ and sympa-developpers ML was CC

**Comment by racke** [comment]
OK please let's add that module for the next release.
